Repository project-origin/wallet, pull requests merged in 2023-10, with the labels that each got.

#101 Renovate/config - abandoned
  .github/renovate.json
Labels: ci

#107 Update mcr.microsoft.com/devcontainers/dotnet Docker tag to v0.204.14
  .devcontainer/Dockerfile
Labels: chore

#102 Update nuget
  src/ProjectOrigin.WalletSystem.Server/ProjectOrigin.WalletSystem.Server.csproj
Labels: chore

#100 Update postgres Docker tag to v16
  src/docker-compose.yaml
Labels: chore

#109 Fixed wrong index for remainder on partial-transfer
  src/ProjectOrigin.WalletSystem.IntegrationTests/TestExtensions/PostgresFixtureExtensions.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/TransferCertificateTests.cs
  src/ProjectOrigin.WalletSystem.Server/Activities/TransferPartialSliceActivity.cs
Labels: bug

#112 Added .dockerignore
  src/.dockerignore
Labels: enhancement

#113 Update nuget
  src/ProjectOrigin.WalletSystem.IntegrationTests/ProjectOrigin.WalletSystem.IntegrationTests.csproj
  src/ProjectOrigin.WalletSystem.Server/ProjectOrigin.WalletSystem.Server.csproj
Labels: chore

#116 Update nuget
  src/ProjectOrigin.WalletSystem.IntegrationTests/ProjectOrigin.WalletSystem.IntegrationTests.csproj
  src/ProjectOrigin.WalletSystem.Server/ProjectOrigin.WalletSystem.Server.csproj
Labels: chore

#115 Update dependency dotnet-sdk to v7.0.402
  .github/workflows/codeql.yaml
  .github/workflows/pullrequest-verify.yml
  .github/workflows/sonarcloud.yaml
  global.json
Labels: chore

#120 fix - migration scripts order
  charts/project-origin-wallet/templates/deployment-wallet.yaml
  src/ProjectOrigin.WalletSystem.Server/ProjectOrigin.WalletSystem.Server.csproj
Labels: bug

#118 First iteration of REST API
  .gitignore
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests.can_query_certificates.verified.txt
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests.can_query_claims.verified.txt
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests.open_api_specification_not_changed.verified.txt
  src/ProjectOrigin.WalletSystem.IntegrationTests/ProjectOrigin.WalletSystem.IntegrationTests.csproj
  src/ProjectOrigin.WalletSystem.IntegrationTests/QueryCertificatesTest.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/TestClassFixtures/GrpcTestFixture.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/WalletSystemTestsBase.cs
  src/ProjectOrigin.WalletSystem.Server/Models/CertificateViewModel.cs
  src/ProjectOrigin.WalletSystem.Server/Models/ClaimViewModel.cs
  src/ProjectOrigin.WalletSystem.Server/ProjectOrigin.WalletSystem.Server.csproj
  src/ProjectOrigin.WalletSystem.Server/Repositories/CertificateRepository.cs
  src/ProjectOrigin.WalletSystem.Server/Services/GRPC/ReceiveSliceService.cs
  src/ProjectOrigin.WalletSystem.Server/Services/GRPC/WalletService.cs
  src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/MapperV1.cs
  src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/ModelsV1.cs
  src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/WalletController.cs
  src/ProjectOrigin.WalletSystem.Server/Startup.cs
Labels: enhancement
