Repository project-origin/wallet, pull requests merged in 2023-11, with the labels that each got.

#127 Update README.md
  README.md
Labels: documentation

#130 Update Renovate GitHub Action to v39.1.1
  .github/workflows/renovate.yaml
Labels: ci

#117 Update nuget
  .devcontainer/Dockerfile
  src/.config/dotnet-tools.json
  src/ProjectOrigin.WalletSystem.IntegrationTests/FlowTests/ClaimTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/ProjectOrigin.WalletSystem.IntegrationTests.csproj
  src/ProjectOrigin.WalletSystem.Server/ProjectOrigin.WalletSystem.Server.csproj
Labels: chore

#119 Update dependency dotnet-sdk to v7.0.403
  global.json
Labels: chore

#123 Add configurable path base
  charts/project-origin-wallet/templates/deployment-wallet.yaml
  charts/project-origin-wallet/values.yaml
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiBasePathTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests.cs
  src/ProjectOrigin.WalletSystem.Server/Options/RestApiOptions.cs
  src/ProjectOrigin.WalletSystem.Server/Services/REST/PathBaseDocumentFilter.cs
  src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/WalletController.cs
  src/ProjectOrigin.WalletSystem.Server/Startup.cs
Labels: enhancement

#125 Expose http1.x
  charts/project-origin-wallet/templates/service-wallet.yaml
  src/ProjectOrigin.WalletSystem.Server/Startup.cs
  src/ProjectOrigin.WalletSystem.Server/appsettings.json
Labels: enhancement

#126 Update doc
  doc/adr/0001-Programming-language.md
  doc/adr/0002-Dapper.md
  doc/adr/0003-gRPC.md
  doc/adr/0004-CQRS.md
  doc/adr/0005-structured-logging.md
  doc/adr/0006-open-telemetry.md
  doc/adr/README.md
  doc/api/index.md
  doc/api/query.md
  doc/contribute/create_release.md
  doc/contribute/toc.yml
  doc/flows/index.md
  doc/flows/issue.md
  doc/flows/receive_slice.md
  doc/flows/transfer.md
  doc/index.md
  doc/toc.yml
Labels: documentation

#131 fixed workflow warning
  .github/workflows/release-published.yaml
Labels: ci

#142 feat: added aggregate query apis
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests.open_api_specification_not_changed.verified.txt
  src/ProjectOrigin.WalletSystem.IntegrationTests/REST/WalletControllerTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/Repositories/CertificateRepositoryTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/TestExtensions/IEnumerableExtensionTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/TestExtensions/PostgresFixtureExtensions.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/TestExtensions/StringExtensionTests.cs
  src/ProjectOrigin.WalletSystem.Server/Extensions/ClaimsPrincipalExtensions.cs
  src/ProjectOrigin.WalletSystem.Server/Extensions/IEnumerableExtensions.cs
  src/ProjectOrigin.WalletSystem.Server/Extensions/StringExtensions.cs
  src/ProjectOrigin.WalletSystem.Server/Models/CertificatesFilter.cs
  src/ProjectOrigin.WalletSystem.Server/Models/TimeAggregate.cs
  src/ProjectOrigin.WalletSystem.Server/Options/RestApiOptions.cs
  src/ProjectOrigin.WalletSystem.Server/ProjectOrigin.WalletSystem.Server.csproj
  src/ProjectOrigin.WalletSystem.Server/Repositories/CertificateRepository.cs
  src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/ModelsV1.cs
  src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/QueryParamsV1.cs
  src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/WalletController.cs
  src/ProjectOrigin.WalletSystem.Server/Startup.cs
Labels: enhancement

#148 Added GetTransfers and AggregateTransfers to the REST api
  global.json
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests.open_api_specification_not_changed.verified.txt
  src/ProjectOrigin.WalletSystem.IntegrationTests/REST/WalletControllerTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/Repositories/CertificateRepositoryTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/TestExtensions/PostgresFixtureExtensions.cs
  src/ProjectOrigin.WalletSystem.Server/Models/TransferFilter.cs
  src/ProjectOrigin.WalletSystem.Server/Models/TransferViewModel.cs
  src/ProjectOrigin.WalletSystem.Server/Repositories/CertificateRepository.cs
  src/ProjectOrigin.WalletSystem.Server/Repositories/ICertificateRepository.cs
  src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/ModelsV1.cs
  src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/WalletController.cs
Labels: enhancement

#144 updated to dotnet 8.0
  .devcontainer/Dockerfile
  global.json
  src/ProjectOrigin.WalletSystem.IntegrationTests/ProjectOrigin.WalletSystem.IntegrationTests.csproj
  src/ProjectOrigin.WalletSystem.Server/Dockerfile
  src/ProjectOrigin.WalletSystem.Server/ProjectOrigin.WalletSystem.Server.csproj
  src/ProjectOrigin.WalletSystem.Server/Startup.cs
Labels: chore

#154 Added automated swaggerhub release
  .github/workflows/release-published.yaml
Labels: documentation, ci

#152 Jwt verification
  charts/project-origin-wallet/run_kind_test.sh
  charts/project-origin-wallet/templates/deployment-wallet.yaml
  charts/project-origin-wallet/values.yaml
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiBasePathTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/FlowTests/AbstractFlowTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/FlowTests/ClaimTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/FlowTests/ReceiveTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/FlowTests/TransferTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/GrpcTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/JwtIssuerTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/JwtTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/MessageBroker/RabbitMqTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/QueryCertificatesTest.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/ReceiveSliceTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/ReceiverDepositEndpointTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/TestClassFixtures/GrpcHelpers/JwtGenerator.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/TestClassFixtures/JwtTokenIssuerFixture.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/TestClassFixtures/TestServerFixture.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/TestClassFixtures/TestServerHelpers/ForwardLoggingProvider.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/TestClassFixtures/TestServerHelpers/TestServerContext.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/WalletSystemTestsBase.cs
  src/ProjectOrigin.WalletSystem.Server/Extensions/JwtBearerOptionsExtensions.cs
  src/ProjectOrigin.WalletSystem.Server/Options/JwtIssuer.cs
  src/ProjectOrigin.WalletSystem.Server/Options/JwtOptions.cs
  src/ProjectOrigin.WalletSystem.Server/Startup.cs
Labels: enhancement, breaking change
