Repository project-origin/wallet, pull requests merged in 2024-04, with the labels that each got.

#263 Fix publish missing secret
  .github/workflows/release-published.yaml
Labels: ci

#254 add-external-postgres-support
  charts/project-origin-wallet/templates/cnpg-cluster.yaml
  charts/project-origin-wallet/templates/deployment-wallet.yaml
  charts/project-origin-wallet/templates/migrate-job.yaml
  charts/project-origin-wallet/values.yaml
Labels: enhancement, breaking change

#266 Add custom manager for Docker image in renovate.json
  .github/renovate.json
Labels: ci

#267 Update Registry version in tests
  src/ProjectOrigin.WalletSystem.IntegrationTests/TestClassFixtures/RegistryFixture.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/rabbitmq.dockerfile
Labels: dependencies

#285 Fix create_wallet_endpoint to include basepath
  charts/project-origin-wallet/templates/deployment-wallet.yaml
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests/ApiBasePathTests.can_create_wallet_endpoint.verified.txt
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests/ApiBasePathTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests/ApiTests.can_create_wallet.verified.txt
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests/ApiTests.can_create_wallet_endpoint.verified.txt
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests/ApiTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/REST/WalletControllerTests.cs
  src/ProjectOrigin.WalletSystem.Server/Options/RestApiOptions.cs
  src/ProjectOrigin.WalletSystem.Server/Options/ServiceOptions.cs
  src/ProjectOrigin.WalletSystem.Server/Services/REST/PathBaseDocumentFilter.cs
  src/ProjectOrigin.WalletSystem.Server/Services/REST/v1/WalletController.cs
  src/ProjectOrigin.WalletSystem.Server/Startup.cs
Labels: bug

#290 Enable header based subject identification
  charts/project-origin-wallet/run_kind_test.sh
  charts/project-origin-wallet/templates/deployment-wallet.yaml
  charts/project-origin-wallet/values.yaml
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests/AuthHeaderTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/ApiTests/AuthJwtTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/Authentication/AuthOptionsTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/Authentication/HeaderOptionsTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/Authentication/JwtIssuerTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/Authentication/JwtTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/CommandHandlers/VerifySliceCommandHandlerTests.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/TelemetryTest/TelemetryIntegrationTest.cs
  src/ProjectOrigin.WalletSystem.IntegrationTests/WalletSystemTestsBase.cs
  src/ProjectOrigin.WalletSystem.Server/Extensions/IConfigurationExtensions.cs
  src/ProjectOrigin.WalletSystem.Server/Extensions/IServiceCollectionExtensions.cs
  src/ProjectOrigin.WalletSystem.Server/Options/AuthOptions.cs
  src/ProjectOrigin.WalletSystem.Server/Options/AuthType.cs
  src/ProjectOrigin.WalletSystem.Server/Options/HeaderOptions.cs
  src/ProjectOrigin.WalletSystem.Server/Services/REST/HeaderAuthenticationHandler.cs
  src/ProjectOrigin.WalletSystem.Server/Startup.cs
Labels: enhancement, breaking change

#302 Updated doc
  doc/api/index.md
  doc/api/open-api.json
Labels: documentation
